In [1]:
import pandas as pd
import numpy as np

In [2]:
#getting the dataset information
df_info = pd.read_csv('ml-100k/u.info',sep='\t', header=None,index_col=False)

In [3]:
df_info

0
0       943 users
1      1682 items
2  100000 ratings

In [4]:
n_users = int(df_info[0][0].split()[0])
print(n_users)

943


In [5]:
n_movies = int(df_info[0][1].split()[0])
print(n_movies)

1682


In [6]:
column_names = ['user_id', 'item_id','rating','timestamp']

In [7]:
df = pd.read_csv('ml-100k/u.data',sep='\t',names=column_names)

In [8]:
df.head()

user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [9]:
df.shape

(100000, 4)

In [10]:
rating = df['rating'].values
max_rating = np.max(rating)
min_rating = np.min(rating)
print(max_rating)
print(min_rating)

5
1


In [11]:
tf = pd.read_csv('ml-100k/u.item',sep='|',header=None)

In [12]:
tf.head()

0                  1            2   3   \
0   1   Toy Story (1995)  01-Jan-1995 NaN   
1   2   GoldenEye (1995)  01-Jan-1995 NaN   
2   3  Four Rooms (1995)  01-Jan-1995 NaN   
3   4  Get Shorty (1995)  01-Jan-1995 NaN   
4   5     Copycat (1995)  01-Jan-1995 NaN   

                                                  4   5   6   7   8   9  ...  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...   0   0   0   1   1 ...   
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...   0   1   1   0   0 ...   
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...   0   0   0   0   0 ...   
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...   0   1   0   0   0 ...   
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)   0   0   0   0   0 ...   

   14  15  16  17  18  19  20  21  22  23  
0   0   0   0   0   0   0   0   0   0   0  
1   0   0   0   0   0   0   0   1   0   0  
2   0   0   0   0   0   0   0   1   0   0  
3   0   0   0   0   0   0   0   0   0   0  
4   0   0   0   0   0   0   0   1   0   0  

[5 rows x 24 columns]

In [13]:
genre_list = pd.read_csv('ml-100k/u.genre',sep='|',header=None)

In [14]:
genre_list

0   1
0       unknown   0
1        Action   1
2     Adventure   2
3     Animation   3
4    Children's   4
5        Comedy   5
6         Crime   6
7   Documentary   7
8         Drama   8
9       Fantasy   9
10    Film-Noir  10
11       Horror  11
12      Musical  12
13      Mystery  13
14      Romance  14
15       Sci-Fi  15
16     Thriller  16
17          War  17
18      Western  18

In [15]:
genre_list

0   1
0       unknown   0
1        Action   1
2     Adventure   2
3     Animation   3
4    Children's   4
5        Comedy   5
6         Crime   6
7   Documentary   7
8         Drama   8
9       Fantasy   9
10    Film-Noir  10
11       Horror  11
12      Musical  12
13      Mystery  13
14      Romance  14
15       Sci-Fi  15
16     Thriller  16
17          War  17
18      Western  18

In [16]:
genre_list = genre_list[0].tolist()

In [17]:
print(genre_list)

['unknown', 'Action', 'Adventure', 'Animation', "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']


In [18]:
n_genres = len(genre_list)
print(n_genres)

19


In [19]:
tf.shape

(1682, 24)

In [20]:
user = pd.read_csv('ml-100k/u.user',sep='|',header=None)

In [21]:
user.head()

0   1  2           3      4
0  1  24  M  technician  85711
1  2  53  F       other  94043
2  3  23  M      writer  32067
3  4  24  M  technician  43537
4  5  33  F       other  15213

In [23]:
user.shape

(943, 5)

In [24]:
theta_users = np.random.randn(n_users,n_genres)
theta_users.shape

(943, 19)

In [25]:
cols = np.r_[5:24]
cols

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23])

In [26]:
movie_features = tf.iloc[:,cols]
movie_features.head()

5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21  22  23
0   0   0   0   1   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0
1   0   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0
3   0   1   0   0   0   1   0   0   1   0   0   0   0   0   0   0   0   0   0
4   0   0   0   0   0   0   1   0   1   0   0   0   0   0   0   0   1   0   0

In [27]:
type(movie_features)

pandas.core.frame.DataFrame

In [28]:
X = movie_features.as_matrix()

In [29]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
X = np.transpose(X)

In [31]:
np.sum(X, axis=0)

array([3, 3, 1, ..., 2, 1, 1], dtype=int64)

In [32]:
sum_X = np.sum(X, axis=0)

In [33]:
sum_X.size

1682

In [34]:
theta = np.divide(X,sum_X)

In [35]:
theta = np.transpose(theta)

In [36]:
theta.shape

(1682, 19)

In [37]:
theta

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.33333333, 0.33333333, ..., 0.33333333, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [38]:
X = theta

In [39]:
X.shape

(1682, 19)

In [40]:
X = np.zeros((n_users,X.shape[1]))